### ISSUE TITLE
[Bug]: - Conflict between alpha_calib_check and weighted CP

### ISSUE THREAD

**Issue by jdalch** [deel-ai/puncc#21]
### Module

Calibration (API)

### Contact Details

dalmau.joseba@gmail.com

### Current Behavior

The function alpha_calib_check is only designed to work for the usual CP, where all weights are equal, it should be adapted to the case of the weighted CP.

### Expected Behavior

Easy solution: call alpha_calib_check only in the case of usual CP, and allow for returning infinity as a quantile in the case of weighted CP.
Better solution: modify alpha_calib_check to take into account the weighted version of CP.

### Version

v0.9

### Environment

```markdown
- OS:
- Python version: 
- Packages used version:
```

### To Reproduce

There is nothing to reproduce.

**Comment by M-Mouhcine** [comment]
Let's go for the first fix to respect the original procedure proposed by the algorithm's authors.
