### ISSUE TITLE
[Feature Request]: - EnbPI for any regression model

### ISSUE THREAD

**Issue by valeman** [deel-ai/puncc#54]
### Module

Regression

### Feature Request

What classes of estimators does EnbPI in PUNCC works with?

The tutorial mentions RandomForest, the EnbPI model as such as published in paper is not limited to bagging estimators and it can work with any model.

Is there a gap in implementation vs the model in the paper?

If so, it would be good to have EnbPI work with any regression model classes including boosted trees (CatBoost/XGBoost/LightGBM) and scikit-learn regressors.

### Version

v0.9

### Environment

```markdown
- OS:
- Python version:
- Packages used version:
```

**Comment by M-Mouhcine** [comment]
Hi @valeman, 

Puncc enables virtually any underlying learning algorithm and aggregation function for EnbPI, including neural networks (pytorch, tf ...), ensemble methods, ... as long as we correctly wrap them with a suitable wrapper (usually `puncc.deel.api.prediction.BasePredictor`).  Here is an synthetic example using different models you can open in colab [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/19UYtecXnIqoQMi2VeSPC9Oxl6ZP4pHT0?usp=sharing).

Let me know if I understood and answered correctly your question.

**Comment by valeman** [comment]
That’s great let me check it out
